sudo: false

language: php

matrix:
    include:
        - php: 7.0
          env: COVERAGE=yes
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

before_install:
    - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;

install:
    - composer require hanneskod/readme-tester:dev-master $COMPOSER_FLAGS --no-interaction

script:
    - vendor/bin/phpeg generate src/Sie4/Grammar.peg
    - if [[ $COVERAGE = yes ]]; then phpunit --verbose --coverage-clover=coverage.clover; fi
    - if [[ $COVERAGE != yes ]]; then phpunit --verbose; fi

after_script:
    - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
