sudo: false

language: php

matrix:
    include:
        - php: 7.1
        - php: 7.0
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer require hanneskod/readme-tester:^1.0@beta $COMPOSER_FLAGS --no-interaction

script:
    - phpunit --verbose
    - phpunit integrations --verbose
    - vendor/bin/readme-tester test README.md docs -v
